spring:
  datasource:
    url: jdbc:oracle:thin:@//<host>:<port>/<service_name>
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: oracle.jdbc.OracleDriver  # evita "driver undefined/unknown"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.hbm2ddl.auto: validate
      jakarta.persistence.schema-generation.database.action: none
      hibernate.dialect: org.hibernate.dialect.OracleDialect

  spring:
    sql:
      init:
        mode: never